defaults:
  - base_encoder

_target_: rayfronts.image_encoders.NARadioEncoder

# Choose from "radio_v2.5-x" where x can be b,l, or g. More models can be found 
# on https://github.com/NVlabs/RADIO/
model_version: radio_v2.5-b

# If text_query is not null, then lang_model cannot be null
lang_model: siglip

# Tuple of ints (height, width) of the input images. Needed to initialize the
# guassian attention window.
input_resolution: ${dataset.rgb_resolution}

# Standard deviation of the gaussian kernel.
gauss_std: 7.

# Whether to return radio features which are not language aligned or whether to 
# project them to the language aligned space directly. If True, then the user 
# can always later use the functions `align_global_features_with_language` or 
# `align_spatial_features_with_language` to project the radio features to be 
# language aligned.
return_radio_features: True